---
name: nokogiri
version: '1.11'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 306d1aec19defeb177e217d8aad9812a52bcd5eb
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
