class DataFile
  def initialize: (String, String, String?) -> void

  def parse_xp_node: (untyped) -> Hash[Symbol, untyped]

  def decode: (String) -> String

  def extract_uri_with_params: () -> void

  def add_debug: (untyped) -> void

  def collect_between: (untyped, untyped) -> Array[untyped]

  def concat: (DataFile) -> void

  def to_a: () -> Array[untyped]

  def to_e: () -> Array[untyped]

  def to_h: () -> Hash[Symbol, untyped]

  def count: (String) -> String

  def countp: (String) -> String

  def kv_xpath: (String, String) -> String

  def collect_form_attributes: () -> void

  def xml: (String) -> void

  BROWSER_OPTIONS: Hash[String, untyped]

  def fetch_body: (String) -> String
end

class Main
  def parse_and_normalize_url: (String?) -> Addressable::URI

  def rewrite_urls_in_document: (Nokogiri::HTML::Document, Addressable::URI) -> Nokogiri::HTML::Document

  def save_response_as_json: (Hash[Symbol, untyped], Addressable::URI) -> void
end